# Generated by Django 5.2.4 on 2025-09-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_swaprequest'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='offered_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_for_trade', to='posts.post'),
        ),
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('swap', 'แลกของ'), ('buy_sell', 'ขาย/รับซื้อ'), ('donate', 'บริจาค')], default='swap', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
