# Generated by Django 5.2.8 on 2025-11-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_amount_request_offered_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user1_status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='user2_status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
