# Generated by Django 5.2.8 on 2025-11-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_user1_status_request_user2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='leaflet_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leaflet_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
