# Generated by Django 5.2.8 on 2025-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_leaflet_lat_request_leaflet_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='leaflet_lat',
            new_name='position_lat',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='leaflet_lng',
            new_name='position_lng',
        ),
        migrations.AddField(
            model_name='request',
            name='user1_position_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='user2_position_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
