# Generated by Django 5.2.8 on 2025-12-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0009_category_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('swap', 'แลกของ'), ('buy_sell', 'ขาย/รับซื้อ'), ('donate', 'บริจาค')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user1_status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user2_status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True)),
                ('position_lat', models.FloatField(blank=True, null=True)),
                ('position_lng', models.FloatField(blank=True, null=True)),
                ('user1_position_confirmed', models.BooleanField(default=False)),
                ('user2_position_confirmed', models.BooleanField(default=False)),
                ('offered_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_for_trade', to='posts.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='posts.post')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
