# Generated by Django 5.2.8 on 2026-01-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user1_deal_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='user2_deal_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
