# Generated by Django 5.2.4 on 2025-08-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_swap_requester_swaprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwapRequest',
        ),
    ]
