# Generated by Django 5.2.4 on 2025-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='leaflet_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='leaflet_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
