# Generated by Django 4.2.24 on 2025-09-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_leaflet_lat_post_leaflet_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('swap', 'แลกของ'), ('buy_sell', 'ขาย/รับซื้อ'), ('donate', 'ให้ฟรี')], max_length=20),
        ),
    ]
