# Generated by Django 5.2.8 on 2025-12-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='swap_item_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_posts', to='posts.category'),
        ),
    ]
