# Generated by Django 5.2.8 on 2025-12-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_swap_swap_item_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swap',
            old_name='swap_item_catagory',
            new_name='swap_item_category',
        ),
    ]
